language: php

php:
- "7.0"
- "7.1"

env:
- WP_VERSION=4.9.1 WP_MULTISITE=0
- WP_VERSION=4.9 WP_MULTISITE=0

before_script:
- composer install --dev --no-interaction
#Coveralls support
- mkdir -p build/logs
- mkdir -p build/cov

script:
- ./vendor/bin/robo tests $WP_VERSION

after_script:
#- php vendor/bin/coveralls -v --dry-run

notifications:
    email:
        recipients:
          - daryl@clubduece.net
        on_success: change
        on_failure: always
